name: Check HTML
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
jobs:
  htmlcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
- name: Lint HTML
  uses: htmlhint/htmlhint-action@v1
        with:
          htmlhint_args: "index.html"
